# Generated by Django 4.2.6 on 2023-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(db_column='id_product', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('nombreprod', models.CharField(db_column='desc_prod', max_length=20)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fechaNacimiento', models.DateField(auto_now_add=True, null=True)),
                ('rut', models.IntegerField(blank=True, null=True)),
                ('dv', models.CharField(max_length=1)),
                ('enfermedad', models.CharField(max_length=20)),
                ('fonocontacto', models.IntegerField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=20)),
                ('editorial', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('hrini', models.CharField(max_length=5)),
                ('hrfin', models.CharField(max_length=5)),
                ('direccion', models.CharField(max_length=20)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
